export const SET_PENDING = "SET_PENDING";

export const DB_FETCH = "DB_FETCH";
export const DB_FETCH_SUCCESS = "DB_FETCH_SUCCESS";
export const DB_FETCH_FAILED = "DB_FETCH_FAILED";

export const DB_ADD_NEW_ENTRY = "DB_ADD_NEW_ENTRY";
export const DB_ADD_NEW_ENTRY_SUCCESS = "DB_ADD_NEW_ENTRY_SUCCESS";
export const DB_ADD_NEW_ENTRY_FAILED = "DB_ADD_NEW_ENTRY_FAILED";

export const DB_DELETE_ITEM = "DB_DELETE_ITEM";
export const DB_DELETE_ITEM_SUCCESS = "DB_DELETE_ITEM_SUCCESS";
export const DB_DELETE_ITEM_FAILED = "DB_DELETE_ITEM_FAILED";

export const DB_DELETE_CATEGORY = "DB_DELETE_CATEGORY";
export const DB_DELETE_CATEGORY_FAILED = "DB_DELETE_CATEGORY_FAILED";

export const DB_EDIT_ITEM = "DB_EDIT_ITEM";
export const DB_EDIT_ITEM_SUCCESS = "DB_EDIT_ITEM_SUCCESS";
export const DB_EDIT_ITEM_FAILED = "DB_EDIT_ITEM_FAILED";

export const GM_COORDINATES_FETCH = "GM_COORDINATES_FETCH";
export const GM_COORDINATES_FETCH_SUCCESS = "GM_COORDINATES_FETCH_SUCCESS";
export const GM_COORDINATES_FETCH_FAILED = "GM_COORDINATES_FETCH_FAILED";

export const EDIT_TOOLBAR_STATE = "EDIT_TOOLBAR_STATE";

export const SET_DEFAULT_EDIT_MODEL = "SET_DEFAULT_EDIT_MODEL";
export const CLEAR_CURRENT_EDIT_MODEL = "CLEAR_CURRENT_EDIT_MODEL";
export const SET_FILTER_STATE = "SET_FILTER_STATE";

export const EDIT_TOOLBAR = "Edit";
export const REMOVE_TOOLBAR = "Remove";
export const ADD_TOOLBAR = "Add";

export const CATEGORIES = "Categories";
export const LOCATIONS = "Locations";
export const BUTTON = "BUTTON";


